# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisakata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='comment',
            field=models.TextField(blank=True, default='詠)', null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='round',
            field=models.CharField(default='1', max_length=3),
        ),
    ]
