# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisakata', '0002_auto_20170617_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='grade',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
    ]
