# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hisakata', '0002_auto_20170613_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='round',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hisakata.Round'),
            preserve_default=False,
        ),
    ]
