# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hisakata', '0003_player_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='round',
        ),
    ]
