# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisakata', '0003_player_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['grade']},
        ),
        migrations.AlterField(
            model_name='player',
            name='grade',
            field=models.IntegerField(choices=[(6, 'ゲスト'), (2, '2年生'), (0, '未登録'), (1, '新入生'), (5, '院生・社会人'), (4, '4年生'), (3, '3年生')], default=0),
        ),
    ]
