# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisakata', '0004_remove_player_round'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='playing',
            options={'ordering': ['player_num']},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['round']},
        ),
        migrations.AddField(
            model_name='round',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
