# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisakata', '0004_auto_20170617_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playing',
            options={'ordering': ['match__round__class_date__date']},
        ),
        migrations.AlterField(
            model_name='player',
            name='grade',
            field=models.IntegerField(choices=[(0, '未登録'), (1, '新入生'), (2, '2年生'), (3, '3年生'), (4, '4年生'), (5, '院生・社会人'), (6, 'ゲスト')], default=0),
        ),
    ]
