# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisakata', '0005_auto_20170616_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
